proxy-providers: {}
proxy-groups: []
rules:
  - SCRIPT,quic,REJECT
  - MATCH,DIRECT
script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
dns:
  default-nameserver: null
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 203.162.4.191
    - 203.162.4.190
    - 210.245.24.20
    - 210.245.24.22
    - 203.113.131.1
    - 203.113.131.2
    - 8.8.4.4
    - 1.0.0.1
log-level: warning
mode: rule
rule-providers: {}
proxies: []
